### ISSUE TITLE
Docker kevoree image and ssl certificate

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#20]
The docker kevoree image after the update to version 5.4.0-SNAPSHOT throws an ssl certificate exception.
Please update its java version and cacerts to include the new registry certificate.

**Comment by maxleiko** [comment]
Done.  

`docker run -it --rm kevoree/java -Dversion=5.4.0-SNAPSHOT` will start the latest runtime using a proper java version.

**Comment by tdalianis** [comment]
Hi actually now it throws another error.

heads@heads-vm:~/kevoree/atcCoreHeads$ docker run -it --rm kevoree/java -Dversion=5.4.0-SNAPSHOT
00:00 INFO: Kevoree bootstrap from mvn:org.kevoree:org.kevoree.bootstrap:5.4.0-SNAPSHOT
00:01 INFO: File resolved remotely, download metaFile
00:03 INFO: File resolved remotely, download metaFile
00:04 INFO: File resolved remotely, download metaFile
00:05 INFO: File resolved remotely, download metaFile
00:05 INFO: File resolved remotely, download metaFile
00:06 INFO: File resolved remotely, download metaFile
00:07 INFO: File resolved remotely, download metaFile
00:16 INFO: Log level= INFO
00:16 INFO: Registry https://registry.kevoree.org:443
00:16 INFO: Starting Kevoree using version: 5.4.0-SNAPSHOT
00:16 INFO: Platform node name: node0
00:16 INFO: Create minimal system with library in version latest
java.lang.Exception: Unable to find kevoree.JavaNode/LATEST/RELEASE on the registry
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.processRegistryTypeDef(KevoreeRegistryResolver.java:69)
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.resolve(KevoreeRegistryResolver.java:105)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:97)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:92)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:87)
        at org.kevoree.kevscript.KevScriptEngine.executeFromStream(KevScriptEngine.java:67)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java:217)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java:247)
        at org.kevoree.bootstrap.Bootstrap.main(Bootstrap.java:333)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kevoree.microkernel.impl.KevoreeMicroKernelImpl$1.run(KevoreeMicroKernelImpl.java:223)

00:17 INFO: Stopping Kevoree
00:17 INFO: Kevoree core stopped
00:17 INFO: Stopped.


The same happens if i provide a kev script with javanode/latest/latest

**Comment by maxleiko** [comment]
Yes of course it uses the `real` address by default `https://registry.kevoree.org:443` which is not released with the new registry currently.  
That's why you have specified `https://kevoree.braindead.fr` in your `~/.kevoree/config.json` on your local machine. Same goes for the Docker container. It needs a proper conf :+1:

**Comment by maxleiko** [comment]
just add `-v ~/.kevoree/config.json:~/.kevoree/config.json` to your command-line and it should work if you have a config.json file on your local machine.

**Comment by maxleiko** [comment]
Give it the whole `$HOME/.kevoree` folder and you will be good yeah.

**Comment by tdalianis** [comment]
heads@heads-vm:~/kevoree/atcCoreHeads$ docker run -it -v /home/heads/.kevoree/config.json:/root/.kevoree/config.json --rm kevoree/java -Dversion=5.4.0-SNAPSHOT
00:00 INFO: Kevoree bootstrap from mvn:org.kevoree:org.kevoree.bootstrap:5.4.0-SNAPSHOT
00:01 INFO: File resolved remotely, download metaFile
00:03 INFO: File resolved remotely, download metaFile
00:04 INFO: File resolved remotely, download metaFile
00:05 INFO: File resolved remotely, download metaFile
00:06 INFO: File resolved remotely, download metaFile
00:07 INFO: File resolved remotely, download metaFile
00:07 INFO: File resolved remotely, download metaFile
00:14 INFO: Log level= INFO
00:14 INFO: Registry https://kevoree.braindead.fr:443
00:14 INFO: Starting Kevoree using version: 5.4.0-SNAPSHOT
00:14 INFO: Platform node name: node0
00:14 INFO: Create minimal system with library in version latest
00:15 INFO: Found kevoree.JavaNode/1/RELEASE in the registry
java.lang.Exception: Unable to find any DeployUnit attached to kevoree.JavaNode/1/RELEASE
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.processRegistryTypeDef(KevoreeRegistryResolver.java:65)
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.resolve(KevoreeRegistryResolver.java:105)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:97)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:92)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:87)
        at org.kevoree.kevscript.KevScriptEngine.executeFromStream(KevScriptEngine.java:67)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java:217)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java:247)
        at org.kevoree.bootstrap.Bootstrap.main(Bootstrap.java:333)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kevoree.microkernel.impl.KevoreeMicroKernelImpl$1.run(KevoreeMicroKernelImpl.java:223)

00:15 INFO: Stopping Kevoree
00:15 INFO: Kevoree core stopped
00:15 INFO: Stopped.

**Comment by maxleiko** [comment]
The default KevScript used by every Kevoree runtime are using RELEASE DepoyUnits. This is the dev branch, there is no RELEASE available yet. You have to specify your own KevScript with LATEST/LATEST as versions.

**Comment by tdalianis** [comment]
Yes if i provide a kev script it works fine! 
Thanks
