### ISSUE TITLE
Jboss Maven resolver issue

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#24]
The new maven resolver throws an exception when i include in my project's pom.xml a certain dependency. The issue could be related to https://issues.jboss.org/browse/SHRINKRES-214 . The jar file is downloaded as supposed to but when i run the project i get 

```
00:15 INFO: Resolving ............. org.kevoree.project:test4:1.0.0-SNAPSHOT
00:22 ERROR: Unable to AddDeployUnit for /nodes[testProcessor]/components[proces
sor]
org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to resolve d
ependencies, none of them were found.
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.getSing
le(MavenFormatStageImpl.java:115)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.asSingl
e(MavenFormatStageImpl.java:107)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.asSingl
eFile(MavenFormatStageImpl.java:56)
        at org.kevoree.bootstrap.kernel.KevoreeCLKernel.installDependencies(Kevo
reeCLKernel.java:102)
        at org.kevoree.bootstrap.kernel.KevoreeCLKernel.installDependencies(Kevo
reeCLKernel.java:116)
        at org.kevoree.bootstrap.kernel.KevoreeCLKernel.installDeployUnit(Kevore
eCLKernel.java:149)
        at org.kevoree.library.java.command.AddDeployUnit.execute(AddDeployUnit.
java:36)
        at org.kevoree.core.deploy.KevoreeSeqDeployPhase.execute(KevoreeSeqDeplo
yPhase.java:27)
        at org.kevoree.core.deploy.PrimitiveCommandExecutionHelper.executeStep(P
rimitiveCommandExecutionHelper.java:44)
        at org.kevoree.core.deploy.PrimitiveCommandExecutionHelper.execute(Primi
tiveCommandExecutionHelper.java:19)
        at org.kevoree.core.KevoreeCoreBean.internal_update_model(KevoreeCoreBea
n.java:343)
        at org.kevoree.core.KevoreeCoreBean$UpdateModelRunnable.run(KevoreeCoreB
ean.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
00:22 ERROR: Error while executing primitive command AddDeployUnit atc/test4/1.0
.0-SNAPSHOT/9a989f7598350060882f1bc945483139
00:22 WARN: JavaSENode is aborting last update...
```

**Comment by maxleiko** [comment]
What did you do in order to get this error ?

**Comment by maxleiko** [comment]
This [commit](https://github.com/dukeboard/kevoree/commit/f063cfb2e935eef87dabc9ad3fe83b5ded26da1e) should fix your issue. You just need to wait a couple of minutes for the new -SNAPSHOT to be released.

**Comment by maxleiko** [comment]
@tdalianis can you tell me if it works so I can close the issue :) ?
