### ISSUE TITLE
RemoteChannel issue

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#31]
Hi 
I am sending a message through a RemoteChannel but when it sends it I get the following error

channel context dispatch 2 >>>>>>>> mvn:org.kevoree.library.java:org.kevoree.library.java.ws:5.4.0-SNAPSHOT
00:55 ERROR: Channel "remote" dispatch threw an exception
java.lang.NoClassDefFoundError: Could not initialize class org.xnio.Xnio
        at org.kevoree.library.RemoteWSChan.lambda$dispatch$5(RemoteWSChan.java:133)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.kevoree.library.RemoteWSChan.dispatch(RemoteWSChan.java:125)
        at org.kevoree.library.java.wrapper.ChannelWrapper.call(ChannelWrapper.java:41)
        at org.kevoree.library.java.wrapper.port.RequiredPortImpl.send(RequiredPortImpl.java:69)
        at org.kevoree.library.java.wrapper.port.RequiredPortImpl.send(RequiredPortImpl.java:58)
        at gr.atc.heads.processors.NamedEntityProcessor.processItem(NamedEntityProcessor.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kevoree.library.java.wrapper.port.ProvidedPortImpl.send(ProvidedPortImpl.java:101)
        at org.kevoree.library.LocalChannel$1.run(LocalChannel.java:40)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

The problem is appeared in the atcHeadsProcessors project, running the main.kevs for NamedEntityProcessor_1

**Comment by tdalianis** [comment]
New version fixed it.
